"""empty message

Revision ID: 120e930e7bac
Revises: 69819f1e9744
Create Date: 2020-08-20 17:33:21.423690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '120e930e7bac'
down_revision = '69819f1e9744'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('label', table_name='todo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('label', 'todo', ['label'], unique=True)
    # ### end Alembic commands ###
