"""empty message

Revision ID: 69819f1e9744
Revises: cbaa38b1e0f1
Create Date: 2020-08-20 17:26:57.515798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69819f1e9744'
down_revision = 'cbaa38b1e0f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('username', table_name='todo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('username', 'todo', ['username'], unique=True)
    # ### end Alembic commands ###
